version: '2'
services:
    php:
      image: dmstr/phd5-app:5.2.0-rc3-debian
      #working_dir: /phd5-docs/.project
      ports:
        - 17200:80
      depends_on:
        - redis
        - db
      environment:
        - DB_ENV_MYSQL_ROOT_PASSWORD=ENTER_A_VERY_STRONG_RANDOM_PASSWORD_HERE
        - DB_ENV_MYSQL_PASSWORD=ENTER_A_STRONG_RANDOM_PASSWORD_HERE
        - DB_ENV_MYSQL_USER=phd
        - DB_ENV_MYSQL_DATABASE=docs
        #- APP_TITLE=phd5 docs
        - APP_CONFIG_FILE=/phd5-docs/.project/config/docs.php
        - APP_ADMIN_EMAIL=docs@phd5.local
        - APP_ADMIN_PASSWORD=admin1
        - APP_MAILER_USE_FILE_TRANSPORT=1
        #- COMPOSER_VENDOR_DIR=/phd5-docs/.project/vendor
        - VIRTUAL_HOST=phd5-docs.localhost

        - YII_ENV=dev
        - YII_DEBUG=1
      volumes:
        # Re-use local composer cache via host-volume
        - ~/.composer-docker/cache:/root/.composer/cache:delegated
        - ../:/phd5-docs
        - ./vendor:/app/vendor
    redis:
        image: redis:3
    db:
      command: --character-set-server=utf8 --collation-server=utf8_general_ci
      environment:
        - MYSQL_ROOT_PASSWORD=ENTER_A_VERY_STRONG_RANDOM_PASSWORD_HERE
        - MYSQL_DATABASE=docs
        - MYSQL_PASSWORD=ENTER_A_STRONG_RANDOM_PASSWORD_HERE
        - MYSQL_USER=phd
      image: 'percona:5.7'
      volumes:
        - ./_host-volumes/mysql:/var/lib/mysql
